# This is a basic workflow to help you get started with Actions

name: Build dependencies

on:

  workflow_dispatch:

jobs:
  
    configure:
    
        runs-on: ubuntu-latest
  
        steps:

            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Git checkout
              uses: actions/checkout@v3

            - name: Generate ID
              id: ID
              shell: sh
              run: echo "::set-output name=ID::$(date +'%Y%m%d%H%M%S')"

    build:

        strategy:
          matrix:
            runsOn: ['ubuntu-latest', 'windows-latest', 'macOs-latest']

        # The type of runner that the job will run on
        runs-on: ${{ matrix.runsOn }}

        steps:

          - name: Configure VCPKG using CMake
            shell: sh
            run: cmake -DMODE=install .

    finalize:

        runs-on: ubuntu-latest

        steps:

          - run: ''
