# This is a basic workflow to help you get started with Actions

name: Build dependencies

on:

  schedule:
    - cron: "0 0 * * Sat"

  workflow_dispatch:

jobs:
  
    configure:
    
        runs-on: ubuntu-latest
  
        outputs:
          release_id: ${{ steps.create_release.outputs.id }}
  
        steps:

            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Git checkout
              uses: actions/checkout@v3

            - name: Generate ID
              id: ID
              shell: sh
              run: echo "::set-output name=ID::$(date +'%Y%m%d%H%M%S')"
              
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              with:
                tag_name: ${{ steps.ID.outputs.ID }}
                release_name: Dependencies ${{ steps.ID.outputs.ID }}
                body: Package of dependencies for build.
                draft: false
                prerelease: true

    build:

        strategy:
          matrix:
            runsOn: ['ubuntu-latest', 'windows-latest', 'macOs-latest']

        # The type of runner that the job will run on
        runs-on: ${{ matrix.runsOn }}

        steps:

          - name: Configure VCPKG using CMake
            shell: sh
            run: cmake -DMODE=install .

    finalize:

        runs-on: ubuntu-latest

        steps:

          - uses: eregon/publish-release@v1
            with:
              release_id: ${{ jobs.configure.outputs.release_id }}
              
          - name: Update version id
            uses: jossef/action-set-json-field@v2
            with:
              file: Versions.json
              field: Dependencies
              value: ${{ jobs.configure.outputs.release_id }}
